# Tkinter SETTINGS
VIEW_WINDOW_SIZE = "300x300"
VIEW_WINDOW_LOCATION = "+20+20"
CTRL_WINDOW_SIZE = "300x300"
CTRL_WINDOW_LOCATION = "+320+320"
PADDING_MAIN = "3 3 12 12"
FONT = "normal"

# GUI MESSAGES
VIEW_APP_NAME = "DJ Viewer"
CONTROL_APP_NAME = "Controller"
CURRENT_BPM = "Current BPM: "
ENTER_BPM = "ENTER BPM: "
SET_BPM = "Set the BPM"
INCREASE_BTN = " >> "
DECREASE_BTN = " << "

